### ISSUE TITLE
Create mixin to handle string localization

### ISSUE THREAD

**Issue by alicoding** [alicoding/react-i18n#1]
@Pomax I would like you to comment on this proposal on how this mixin should work.

So, I'm thinking of creating a library that will handle all the strings, but it will work in a way that we can narrow it down like a dictionary.

For example, if we have 3 components and 3 languages the structure might be something like this:

``` json
{
  "ComponentHeader": {
    "en": {
      ...
    },
    "th": {
      ...
    },
    "ru": {
      ...
    }
  },
  "ComponentFooter": {
    "en": {
      ...
    },
    "th": {
      ...
    },
    "ru": {
      ...
    }
  },
  "ComponentEditor": {
    "en": {
      ...
    },
    "th": {
      ...
    },
    "ru": {
      ...
    }
  }
}
```

The advantage of doing this is we can easily require in just the necessary strings for that component only instead of requiring the whole JSON for the application (if we have 10 components and 100 languages O_o). Another advantage here is that we will be able to maintain and monitor strings add/remove for that specific component and we will be able to change them easily on Transifex or whichever platform for localization we use here.

 Obviously the structure for the JSON file that we upload on Transifex will still be the same which is plain JSON or `chrome-i18n JSON` whichever we choose to use, but the build step is what makes it the way I describe above.

**Comment by Pomax** [comment]
fun fact: JSON needs double quotes. Single quotes are illegal.

**Comment by Pomax** [comment]
actual comments:

As long as we can automate the aggregation, this seems very sensible to me. However, it's worth bearing in mind @davidascher's advice in https://github.com/MozillaFoundation/mofo-example-app/issues/13#issuecomment-71950068 -- let's take finding the right answers onto the web, too.

As a structure that we can optimise, this looks promising. If it's easy to build with, or using, existing tools, that's great, let's get automating.
